#!/usr/bin/env python3
"""
Auto-send the follow-ups generated by followup_scheduler.py (/tmp/followups_to_send.json).

Runs in CI right after the scheduler. Sends each due follow-up via SMTP (same secrets
as the orchestrator), capped per run, then emails Nuredin a summary of what was sent.
Resilient: missing/empty input exits 0; a per-recipient failure never kills the run.
"""

import json
import os
import smtplib
import socket
import sys
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path

socket.setdefaulttimeout(60)

INPUT = Path("/tmp/followups_to_send.json")
CAP = int(os.environ.get("FOLLOWUP_DAILY_CAP", "10"))

SMTP_HOST = os.environ.get("SMTP_HOST", "smtp.gmail.com")
SMTP_PORT = int(os.environ.get("SMTP_PORT", "587"))
SMTP_USER = os.environ.get("SMTP_USER", "")
SMTP_PASSWORD = os.environ.get("SMTP_PASSWORD", "")
SMTP_FROM = os.environ.get("SMTP_FROM", SMTP_USER)
SMTP_USE_SSL = os.environ.get("SMTP_USE_SSL", "0") == "1"
RECIPIENT = os.environ.get("REPORT_RECIPIENT", "nuredinmohamedali@gmail.com")


def smtp_connect():
    if SMTP_USE_SSL:
        server = smtplib.SMTP_SSL(SMTP_HOST, SMTP_PORT, timeout=30)
    else:
        server = smtplib.SMTP(SMTP_HOST, SMTP_PORT, timeout=30)
        server.ehlo()
        server.starttls()
        server.ehlo()
    server.login(SMTP_USER, SMTP_PASSWORD)
    return server


def main():
    if not SMTP_PASSWORD:
        print("[INFO] SMTP secrets not set - skipping auto-send")
        return 0
    if not INPUT.exists():
        print("[INFO] no followups file - nothing to send")
        return 0
    followups = json.loads(INPUT.read_text(encoding="utf-8"))
    if not followups:
        print("[INFO] 0 follow-ups due - nothing to send")
        return 0

    sent, failed = [], []
    for fu in followups[:CAP]:
        to = (fu.get("email") or "").strip()
        if "@" not in to:
            failed.append((fu.get("company"), "no email"))
            continue
        msg = MIMEMultipart()
        msg["From"] = SMTP_FROM
        msg["To"] = to
        msg["Subject"] = fu["subject"]
        msg["Reply-To"] = os.environ.get("REPLY_TO_ADDRESS", "nuredinmohamedali@gmail.com")
        msg.attach(MIMEText(fu["body"], "plain", "utf-8"))
        try:
            with smtp_connect() as server:
                server.send_message(msg)
            sent.append((fu["company"], to, fu["version"]))
            print(f"[OK] follow-up {fu['version']} -> {fu['company']} <{to}>")
        except Exception as e:  # noqa: BLE001
            failed.append((fu["company"], str(e)))
            print(f"[WARN] failed {fu['company']}: {e}", file=sys.stderr)

    skipped = max(0, len(followups) - CAP)

    # Summary to Nuredin
    lines = [f"Follow-ups auto-sent: {len(sent)} (failed: {len(failed)}, deferred beyond cap: {skipped})", ""]
    for c, to, v in sent:
        lines.append(f"  - {c} <{to}> (version {v})")
    if failed:
        lines.append("")
        lines.append("Failed:")
        for c, why in failed:
            lines.append(f"  - {c}: {why}")
    body = "\n".join(lines)
    try:
        msg = MIMEMultipart()
        msg["From"] = SMTP_FROM
        msg["To"] = RECIPIENT
        msg["Subject"] = f"[Job Madinah] {len(sent)} follow-ups sent automatically"
        msg.attach(MIMEText(body, "plain", "utf-8"))
        with smtp_connect() as server:
            server.send_message(msg)
    except Exception as e:  # noqa: BLE001
        print(f"[WARN] summary email failed: {e}", file=sys.stderr)

    print(f"[OK] done: {len(sent)} sent, {len(failed)} failed, {skipped} deferred")
    return 0


if __name__ == "__main__":
    sys.exit(main())
